# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
#  api-app:
#    image: api
#    environment:
#      - _JAVA_OPTIONS=-Xmx512m -Xms256m
#      # - SPRING_PROFILES_ACTIVE=dev,api-docs
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://vps52197.publiccloud.com.br:5433/postgres
#      - SPRING_LIQUIBASE_URL=jdbc:postgresql://vps52197.publiccloud.com.br:5433/postgres
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#      - SPRING_PROFILES_ACTIVE=prod,api-docs
#      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
#      #      - SPRING_DATASOURCE_URL=jdbc:postgresql://195.35.40.91:5432/osgestor
#      #      - SPRING_LIQUIBASE_URL=jdbc:postgresql://195.35.40.91:5432/osgestor
#      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
#    ports:
#      - 8081:8080
   postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
